### PR TITLE
Change kubefin to kubefin-system

### LINKED ISSUE #65: Change namespace kubefin to kubefin-system
Seems most of project put their component in XXX-system namespace. Do we need to update kubefin to kubefin-system?

### PR DESCRIPTION
**Pull request by REestrella**
Fixes #65

### CODE REVIEW

**Comment by mrhello369** [comment]
Hi, @REestrella 
Can you help fix the e2e failure

**Comment by mrhello369** [comment]
/retitle feat: change kubefin ns to kubefin-system ns

**Comment by mrhello369** [comment]
/retitle feat: change kubefin ns to kubefin-system ns

**Comment by mrhello369** [comment]
/retitle feat: change kubefin ns to kubefin-system ns

**Review by francis-jjk — APPROVED** [review]
lgtm

**Pull request merged**
